name: Deploy to Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name : Checkout code
          uses: actions/checkout@v2
        - name : Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.11.1'
        - name : Install dependencies
          run : npm install
        - name : Build project
          run : npm run build
        - name : Deploy to Render
          env : 
            RENDER_API_KEY: ${{ secrets.NEXT_PUBLIC_RENDER_API_KEY }}
          run : 